import {layout,camera} from './graph.mjs';
const $=s=>document.querySelector(s);
const [{trees},atlas]=await Promise.all([fetch('/catalog.json').then(r=>r.json()),fetch('assets/realistic-v3.json').then(r=>r.json())]);
let tree,graph,view,zoom=.5,pan=0,panY=0,selected=null,gesture=null;
const svgNS='http://www.w3.org/2000/svg';
function sprite(el,id){
 const a=atlas.mapping[id],region=document.createElement('div'),size=Math.max(a.cropWidth,a.cropHeight);
 region.className='sprite-region';
 region.style.width=`${a.cropWidth/size*100}%`;region.style.height=`${a.cropHeight/size*100}%`;
 region.style.backgroundImage=`url("${a.file}")`;
 region.style.backgroundSize=`${a.imageWidth/a.cropWidth*100}% ${a.imageHeight/a.cropHeight*100}%`;
 region.style.backgroundPosition=`${a.cropX*100/(a.imageWidth-a.cropWidth)}% ${a.cropY*100/(a.imageHeight-a.cropHeight)}%`;
 el.replaceChildren(region);
}
function svg(tag,attributes){const el=document.createElementNS(svgNS,tag);for(const [k,v]of Object.entries(attributes))el.setAttribute(k,v);return el;}
for(const t of trees){const b=document.createElement('button');b.textContent=t.title;const s=document.createElement('span');s.textContent=t.nodes.length;b.append(s);b.dataset.tree=t.id;b.onclick=()=>show(t);$('#trees').append(b);const o=new Option(t.title,t.id);$('#tree-select').append(o);}
$('#tree-select').onchange=e=>show(trees.find(t=>t.id===e.target.value));
function show(t){tree=t;graph=layout(t);zoom=.5;pan=panY=0;selected=null;$('#zoom').value=0;$('#tree-select').value=t.id;for(const b of $('#trees').children)b.classList.toggle('active',b.dataset.tree===t.id);$('#title').textContent=t.title;$('#count').textContent=`${t.nodes.length} Technologien · ${graph.edges.length} Verbindungen`;$('#nodes').replaceChildren();$('#wires').replaceChildren();$('#wires').setAttribute('width',graph.width);$('#wires').setAttribute('height',graph.height);
for(const e of graph.edges){const d=e.points.map((p,i)=>(i?'L':'M')+p.join(',')).join(' ');$('#wires').append(svg('path',{d,class:'wire-shadow'}),svg('path',{d,class:'wire'}));for(const p of [e.start,e.end]){const dock=svg('rect',{class:'dock',rx:0});dock.dataset.x=p[0];dock.dataset.y=p[1];$('#wires').append(dock);}}
for(const n of graph.nodes.values()){const b=document.createElement('button');b.className='node'+(n.known?' known':'');b.style.left=n.x+'px';b.style.top=n.y+'px';b.dataset.id=n.id;b.setAttribute('aria-label',n.name);const pic=document.createElement('div');pic.className='picture';sprite(pic,n.id);b.append(pic);b.onclick=e=>{if(e.detail===0)details(n.id);};$('#nodes').append(b);}render();}
function render(){const box=$('#viewport').getBoundingClientRect();view=camera(graph,box.width-2,box.height-2,zoom,pan,panY);pan=view.pan;panY=view.panY;$('#world').style.transform=`translate(${view.x}px,${view.y}px) scale(${view.scale})`;const size=5/view.scale;for(const d of document.querySelectorAll('.dock')){d.setAttribute('x',Number(d.dataset.x)-size/2);d.setAttribute('y',Number(d.dataset.y)-size/2);d.setAttribute('width',size);d.setAttribute('height',size);}}
function details(id){selected=id;const n=graph.nodes.get(id);for(const b of $('#nodes').children)b.classList.toggle('selected',b.dataset.id===id);sprite($('#detail-image'),id);$('#status').textContent=n.known?'STARTWISSEN':'TECHNOLOGIEENTWURF';$('#name').textContent=n.name;$('#kind').textContent=n.upgrade?'Verbesserbare Technologie':'Forschung / technischer Ausbau';function list(selector,ids,empty){$(selector).replaceChildren();for(const text of ids.length?ids.map(id=>graph.nodes.get(id)?.name??id):[empty]){const li=document.createElement('li');li.textContent=text;$(selector).append(li);}}list('#parents',n.parents,'Keine lokalen Vorgänger');list('#children',graph.edges.filter(e=>e.source===id).map(e=>e.target),'Endpunkt dieses Zweigs');$('#notes').textContent=tree.note??'';$('#requirements').textContent=(tree.requirements??'').replaceAll('\\n','\n');$('#detail').showModal();}
$('#detail .close').onclick=()=>$('#detail').close();$('#detail').onclick=e=>{if(e.target===$('#detail')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}};
$('#zoom').oninput=e=>{zoom=Number(e.target.value)/100;render();};$('#fit').onclick=()=>{zoom=.5;pan=panY=0;$('#zoom').value=0;render();};
const vp=$('#viewport');vp.onpointerdown=e=>{if(e.button!==0)return;gesture={id:e.pointerId,x:e.clientX,y:e.clientY,startPan:pan,startPanY:panY,node:e.target.closest('.node')?.dataset.id,moved:false};vp.setPointerCapture(e.pointerId);};vp.onpointermove=e=>{if(!gesture)return;const dx=e.clientX-gesture.x,dy=e.clientY-gesture.y;if(Math.hypot(dx,dy)>5)gesture.moved=true;if(gesture.moved){pan=gesture.startPan+dx;panY=gesture.startPanY+dy;vp.classList.add('dragging');render();}};vp.onpointerup=e=>{if(!gesture)return;const g=gesture;gesture=null;vp.classList.remove('dragging');if(!g.moved&&g.node)details(g.node);};vp.onpointercancel=()=>{gesture=null;vp.classList.remove('dragging');};vp.onwheel=e=>{e.preventDefault();zoom=Math.max(0,Math.min(1,zoom-e.deltaY*.001));$('#zoom').value=Math.round(zoom*100);render();};new ResizeObserver(()=>graph&&render()).observe(vp);show(trees[0]);
